[tool.poetry]
name = "research-assistant"
version = "0.0.1"
description = "Uses GPT Researcher as a research agent"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.313, <0.1"
openai = "<2"
beautifulsoup4 = "^4.12.2"
duckduckgo-search = "^3.9.5"
tavily-python = "^0.2.6"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "research_assistant"
export_attr = "chain"

[tool.templates-hub]
use-case = "research"
author = "LangChain"
integrations = ["OpenAI"]
tags = ["data", "agents"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
